export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_REQUEST_SUCCESS = "CREATE_ORDER_REQUEST_SUCCESS";
export const CREATE_ORDER_REQUEST_FAIL = "CREATE_ORDER_REQUEST_FAIL";

export const MY_ORDER_REQUEST = "MY_ORDER_REQUEST";
export const MY_ORDER_REQUEST_SUCCESS = "MY_ORDER_REQUEST_SUCCESS";
export const MY_ORDER_REQUEST_FAIL = "MY_ORDER_REQUEST_FAIL";

export const ALL_ORDER_REQUEST = "ALL_ORDER_REQUEST";
export const ALL_ORDER_REQUEST_SUCCESS = "ALL_ORDER_REQUEST_SUCCESS";
export const ALL_ORDER_REQUEST_FAIL = "ALL_ORDER_REQUEST_FAIL";

export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_REQUEST_SUCCESS = "UPDATE_ORDER_REQUEST_SUCCESS";
export const UPDATE_ORDER_REQUEST_FAIL = "UPDATE_ORDER_REQUEST_FAIL";
export const UPDATE_ORDER_REQUEST_RESET = "UPDATE_ORDER_REQUEST_RESET";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_REQUEST_SUCCESS = "DELETE_ORDER_REQUEST_SUCCESS";
export const DELETE_ORDER_REQUEST_FAIL = "DELETE_ORDER_REQUEST_FAIL";
export const DELETE_ORDER_REQUEST_RESET = "DELETE_ORDER_REQUEST_RESET";

export const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST";
export const ORDER_DETAIL_REQUEST_SUCCESS = "ORDER_DETAIL_REQUEST_SUCCESS";
export const ORDER_DETAIL_REQUEST_FAIL = "ORDER_DETAIL_REQUEST_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
