export const GET_All_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_All_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_All_PRODUCTS_FAIL = "GET_ALL_PRODUCTS_FAIL";

export const GET_ADMIN_PRODUCTS = "GET_ADMIN_PRODUCTS";
export const GET_ADMIN_PRODUCTS_SUCCESS = "GET_ADMIN_PRODUCTS_SUCCESS";
export const GET_ADMIN_PRODUCTS_FAIL = "GET_ADMIN_PRODUCTS_FAIL";

export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_REQUEST_SUCCESS = "DELETE_PRODUCT_REQUEST_SUCCESS";
export const DELETE_PRODUCT_REQUEST_FAIL = "DELETE_PRODUCT_REQUEST_FAIL";
export const DELETE_PRODUCT_REQUEST_RESET = "DELETE_PRODUCT_REQUEST_RESET";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_REQUEST_SUCCESS = "UPDATE_PRODUCT_REQUEST_SUCCESS";
export const UPDATE_PRODUCT_REQUEST_FAIL = "UPDATE_PRODUCT_REQUEST_FAIL";
export const UPDATE_PRODUCT_REQUEST_RESET = "UPDATE_PRODUCT_REQUEST_RESET";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_REQUEST_SUCCESS = "NEW_REVIEW_REQUEST_SUCCESS";
export const NEW_REVIEW_REQUEST_FAIL = "NEW_REVIEW_REQUEST_FAIL";
export const NEW_REVIEW_REQUEST_RESET = "NEW_REVIEW_REQUEST_RESET";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_REQUEST_SUCCESS = "NEW_PRODUCT_REQUEST_SUCCESS";
export const NEW_PRODUCT_REQUEST_FAIL = "NEW_PRODUCT_REQUEST_FAIL";
export const NEW_PRODUCT_REQUEST_RESET = "NEW_PRODUCT_REQUEST_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
